version: '3.8'
services:
    cache-master:
        build: ./cache-master
        container_name: cache-master
        tty: true
        volumes: 
            - ./cache-master:/cache-master
        restart: always
        ports:
            - 6666:6666

    cache-slave1-replica1:
        build: ./cache-slave
        container_name: cache-slave1-replica1
        tty: true
        restart: always
        depends_on: [cache-master]
        environment:
            - SLAVE_NAME=cache-slave1

    cache-slave1-replica2:
        build: ./cache-slave
        container_name: cache-slave1-replica2
        tty: true
        restart: always
        depends_on: [cache-master]
        environment:
            - SLAVE_NAME=cache-slave1

    cache-slave2-replica1:
        build: ./cache-slave
        container_name: cache-slave2-replica1
        tty: true
        restart: always
        depends_on: [cache-master]
        environment:
            - SLAVE_NAME=cache-slave2
